[[redirects]]
    from = "/*"
    to = "https://port-0-portfolio-v2-backend-3prof2lll3bfr1i.sel3.cloudtype.app/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "https://oieho.netlify.app/:splat"
    status = 200