[build]
    command = "npm run build"
    publish = "build"
[[redirects]]
    from = "https://legendary-pony-913426.netlify.app/*"
    to = "https://port-0-portfolio-v2-backend-3prof2lll3bfr1i.sel3.cloudtype.app/:splat"
    status = 200